title: Dihara Wijetunga
description: Graphics Programming, Game Developement and other shady business.

url: http://diharaw.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Blog
   url: /index.html
 - title: Projects
   url: /projects
 - title: About
   url: /about
 - title: Resume
   url: /resume

social:
   github: diharaw
   twitter: diharaw94
   facebook: diharaw
   email: dihara.w94@gmail.com

google_analytics: "UA-58263416-1"
